-- Weather Analysis Results Table
-- Stores pre-computed analysis, severity levels, and insights for weather metrics

CREATE TABLE IF NOT EXISTS weather_analysis (
    id SERIAL PRIMARY KEY,
    
    -- Station information
    station_id INTEGER REFERENCES bom_weather_stations(id) ON DELETE CASCADE,
    station_name VARCHAR(255) NOT NULL,
    
    -- Metric type (temperature, humidity, wind_speed, etc.)
    metric_type VARCHAR(50) NOT NULL,
    
    -- Time period for the analysis
    analysis_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    period_days INTEGER NOT NULL, -- typically 7 for weekly analysis
    
    -- Computed statistics
    current_value DECIMAL(10, 3),
    average_value DECIMAL(10, 3),
    min_value DECIMAL(10, 3),
    max_value DECIMAL(10, 3),
    variance_pct DECIMAL(5, 2),
    change_pct DECIMAL(5, 2), -- percentage change from previous period
    
    -- Severity/Level classification
    severity_level VARCHAR(20), -- 'low', 'moderate', 'high', 'extreme'
    trend VARCHAR(20), -- 'increasing', 'decreasing', 'stable'
    
    -- Analysis text (generated by AI or rule-based system)
    analysis_text TEXT NOT NULL,
    short_summary VARCHAR(255),
    
    -- Metadata
    analysis_version VARCHAR(20) DEFAULT '1.0',
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confidence_score DECIMAL(3, 2), -- 0.0 to 1.0
    
    -- Indexing for fast lookups
    CONSTRAINT unique_station_metric_date UNIQUE (station_name, metric_type, analysis_date)
);

-- Indexes for performance
CREATE INDEX idx_weather_analysis_station ON weather_analysis(station_name);
CREATE INDEX idx_weather_analysis_metric ON weather_analysis(metric_type);
CREATE INDEX idx_weather_analysis_date ON weather_analysis(analysis_date);
CREATE INDEX idx_weather_analysis_severity ON weather_analysis(severity_level);

-- Example data for testing
-- INSERT INTO weather_analysis (
--     station_name, metric_type, analysis_date, 
--     period_start, period_end, period_days,
--     current_value, average_value, min_value, max_value,
--     variance_pct, change_pct, severity_level, trend,
--     analysis_text, short_summary, confidence_score
-- ) VALUES (
--     'Sydney Observatory Hill', 'temperature', CURRENT_DATE,
--     CURRENT_DATE - INTERVAL '7 days', CURRENT_DATE, 7,
--     22.5, 21.8, 18.2, 25.6,
--     15.2, -2.3, 'moderate', 'decreasing',
--     'Temperature has remained relatively stable, with an average of 21.8°C. There was a slight decrease of 2.3% over the last week, indicating a mild and consistent weather pattern. Daily variance of 15.2% suggests moderate temperature fluctuations.',
--     'Mild temperatures with slight cooling trend',
--     0.95
-- );

COMMENT ON TABLE weather_analysis IS 'Stores pre-computed weather analysis results including statistics, severity levels, and AI-generated insights';
COMMENT ON COLUMN weather_analysis.severity_level IS 'Classification: low, moderate, high, extreme based on metric-specific thresholds';
COMMENT ON COLUMN weather_analysis.trend IS 'Directional trend: increasing, decreasing, stable';
COMMENT ON COLUMN weather_analysis.confidence_score IS 'Analysis confidence from 0.0 to 1.0, based on data quality and completeness';
